# Generated by Django 4.2.2 on 2023-06-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_photo_alter_profile_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram',
            field=models.URLField(blank=True),
        ),
    ]
